/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AdminPermissions: () => import('#controllers/admin_permissions_controller'),
  AdminRoles: () => import('#controllers/admin_roles_controller'),
  AdminSecurity: () => import('#controllers/admin_security_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
  UploadConfig: () => import('#controllers/upload_config_controller'),
  UploadedFiles: () => import('#controllers/uploaded_files_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
