/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AdminPermissions: () => import('#controllers/admin_permissions_controller'),
  AdminRoles: () => import('#controllers/admin_roles_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
  Attachments: () => import('#controllers/attachments_controller'),
  UploadCleanup: () => import('#controllers/upload_cleanup_controller'),
  UploadConfig: () => import('#controllers/upload_config_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
}
