/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AdminPermissions: () => import('#controllers/admin_permissions_controller'),
  AdminRoles: () => import('#controllers/admin_roles_controller'),
  AdminUsers: () => import('#controllers/admin_users_controller'),
}
