import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('admin_attachments', (table) => {
      table.increments('id').notNullable()
      table.uuid('uuid').notNullable()
      table
        .integer('parent_attachment_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('admin_attachments')
        .withKeyName('att_parent_fk')
        .onDelete('CASCADE')
      table.string('original_name', 255).notNullable()
      table.string('storage_disk', 32).notNullable()
      table.string('storage_path', 512).nullable()
      table.string('object_key', 512).nullable()
      table.string('url', 512).nullable()
      table.string('extension', 32).nullable()
      table.string('mime_type', 128).notNullable()
      table.string('file_type', 32).notNullable()
      table.bigInteger('size').unsigned().notNullable()
      table.string('hash', 64).nullable()
      table.integer('width').unsigned().nullable()
      table.integer('height').unsigned().nullable()
      table.integer('duration').unsigned().nullable()
      table.string('status', 32).notNullable()
      table.string('upload_mode', 32).notNullable()
      table.string('upload_token', 64).notNullable()
      table
        .integer('uploader_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_users')
        .withKeyName('att_uploader_fk')
        .onDelete('RESTRICT')
      table.boolean('is_complete').notNullable().defaultTo(false)
      table.text('error_message').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
      table.timestamp('last_used_at').nullable()
      table.timestamp('bound_at').nullable()
      table.timestamp('expires_at').nullable()
      table.timestamp('deleted_at').nullable()
      table.unique(['uuid'], 'att_uuid_uq')
      table.index(['status'], 'att_status_idx')
      table.index(['upload_token'], 'att_token_idx')
      table.index(['expires_at'], 'att_expires_idx')
      table.index(['uploader_id', 'status'], 'att_uploader_status_idx')
      table.index(['hash', 'size'], 'att_hash_size_idx')
    })

    this.schema.createTable('admin_attachment_relations', (table) => {
      table.increments('id').notNullable()
      table
        .integer('attachment_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_attachments')
        .withKeyName('att_rel_attachment_fk')
        .onDelete('CASCADE')
      table.string('business_type', 64).notNullable()
      table.string('business_id', 64).notNullable()
      table.string('field_name', 64).notNullable()
      table.integer('sort').unsigned().notNullable().defaultTo(0)
      table.timestamp('created_at').notNullable()
      table.unique(
        ['attachment_id', 'business_type', 'business_id', 'field_name'],
        'att_rel_business_uq'
      )
      table.index(['business_type', 'business_id', 'field_name'], 'att_rel_business_idx')
    })

    this.schema.createTable('admin_upload_sessions', (table) => {
      table.increments('id').notNullable()
      table.uuid('upload_id').notNullable()
      table.string('upload_token', 64).notNullable()
      table
        .integer('attachment_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_attachments')
        .withKeyName('upload_attachment_fk')
        .onDelete('CASCADE')
      table.string('original_name', 255).notNullable()
      table.string('mime_type', 128).notNullable()
      table.bigInteger('file_size').unsigned().notNullable()
      table.string('file_hash', 64).nullable()
      table.integer('chunk_size').unsigned().notNullable()
      table.integer('chunk_total').unsigned().notNullable()
      table.integer('uploaded_chunks').unsigned().notNullable().defaultTo(0)
      table.string('storage_upload_id', 255).nullable()
      table.string('status', 32).notNullable()
      table
        .integer('uploader_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_users')
        .withKeyName('upload_uploader_fk')
        .onDelete('RESTRICT')
      table.text('error_message').nullable()
      table.timestamp('expires_at').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
      table.unique(['upload_id'], 'upload_id_uq')
      table.index(['upload_token'], 'upload_token_idx')
      table.index(['status'], 'upload_status_idx')
      table.index(['expires_at'], 'upload_expires_idx')
      table.index(['uploader_id', 'status'], 'upload_uploader_status_idx')
    })

    this.schema.createTable('admin_upload_chunks', (table) => {
      table.increments('id').notNullable()
      table
        .integer('upload_session_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_upload_sessions')
        .withKeyName('chunk_session_fk')
        .onDelete('CASCADE')
      table.integer('chunk_index').unsigned().notNullable()
      table.integer('size').unsigned().notNullable()
      table.string('hash', 64).notNullable()
      table.string('etag', 255).nullable()
      table.string('storage_path', 512).notNullable()
      table.boolean('is_complete').notNullable().defaultTo(true)
      table.timestamp('uploaded_at').notNullable()
      table.unique(['upload_session_id', 'chunk_index'], 'chunk_session_index_uq')
    })
  }

  async down() {
    this.schema.dropTable('admin_upload_chunks')
    this.schema.dropTable('admin_upload_sessions')
    this.schema.dropTable('admin_attachment_relations')
    this.schema.dropTable('admin_attachments')
  }
}
