import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    this.schema.createTable('admin_attachments', (table) => {
      table.increments('id').notNullable()
      table.uuid('uuid').notNullable().unique()
      table
        .integer('parent_attachment_id')
        .unsigned()
        .nullable()
        .references('id')
        .inTable('admin_attachments')
        .onDelete('CASCADE')
      table.string('original_name', 255).notNullable()
      table.string('storage_disk', 32).notNullable()
      table.string('storage_path', 512).nullable()
      table.string('object_key', 512).nullable()
      table.string('url', 512).nullable()
      table.string('extension', 32).nullable()
      table.string('mime_type', 128).notNullable()
      table.string('file_type', 32).notNullable()
      table.bigInteger('size').unsigned().notNullable()
      table.string('hash', 64).nullable()
      table.integer('width').unsigned().nullable()
      table.integer('height').unsigned().nullable()
      table.integer('duration').unsigned().nullable()
      table.string('status', 32).notNullable().index()
      table.string('upload_mode', 32).notNullable()
      table.string('upload_token', 64).notNullable().index()
      table
        .integer('uploader_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_users')
        .onDelete('RESTRICT')
      table.boolean('is_complete').notNullable().defaultTo(false)
      table.text('error_message').nullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
      table.timestamp('last_used_at').nullable()
      table.timestamp('bound_at').nullable()
      table.timestamp('expires_at').nullable().index()
      table.timestamp('deleted_at').nullable()
      table.index(['uploader_id', 'status'])
      table.index(['hash', 'size'])
    })

    this.schema.createTable('admin_attachment_relations', (table) => {
      table.increments('id').notNullable()
      table
        .integer('attachment_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_attachments')
        .onDelete('CASCADE')
      table.string('business_type', 64).notNullable()
      table.string('business_id', 64).notNullable()
      table.string('field_name', 64).notNullable()
      table.integer('sort').unsigned().notNullable().defaultTo(0)
      table.timestamp('created_at').notNullable()
      table.unique(['attachment_id', 'business_type', 'business_id', 'field_name'])
      table.index(['business_type', 'business_id', 'field_name'])
    })

    this.schema.createTable('admin_upload_sessions', (table) => {
      table.increments('id').notNullable()
      table.uuid('upload_id').notNullable().unique()
      table.string('upload_token', 64).notNullable().index()
      table
        .integer('attachment_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_attachments')
        .onDelete('CASCADE')
      table.string('original_name', 255).notNullable()
      table.string('mime_type', 128).notNullable()
      table.bigInteger('file_size').unsigned().notNullable()
      table.string('file_hash', 64).nullable()
      table.integer('chunk_size').unsigned().notNullable()
      table.integer('chunk_total').unsigned().notNullable()
      table.integer('uploaded_chunks').unsigned().notNullable().defaultTo(0)
      table.string('storage_upload_id', 255).nullable()
      table.string('status', 32).notNullable().index()
      table
        .integer('uploader_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_users')
        .onDelete('RESTRICT')
      table.text('error_message').nullable()
      table.timestamp('expires_at').notNullable().index()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').nullable()
      table.index(['uploader_id', 'status'])
    })

    this.schema.createTable('admin_upload_chunks', (table) => {
      table.increments('id').notNullable()
      table
        .integer('upload_session_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('admin_upload_sessions')
        .onDelete('CASCADE')
      table.integer('chunk_index').unsigned().notNullable()
      table.integer('size').unsigned().notNullable()
      table.string('hash', 64).notNullable()
      table.string('etag', 255).nullable()
      table.string('storage_path', 512).notNullable()
      table.boolean('is_complete').notNullable().defaultTo(true)
      table.timestamp('uploaded_at').notNullable()
      table.unique(['upload_session_id', 'chunk_index'])
    })
  }

  async down() {
    this.schema.dropTable('admin_upload_chunks')
    this.schema.dropTable('admin_upload_sessions')
    this.schema.dropTable('admin_attachment_relations')
    this.schema.dropTable('admin_attachments')
  }
}
