/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AdminAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdminPermissionSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'id',
    'name',
    'status',
    'updatedAt',
  ] as const
  $columns = AdminPermissionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdminRolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId', 'updatedAt'] as const
  $columns = AdminRolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare permissionId: number
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdminRoleSchema extends BaseModel {
  static $columns = [
    'code',
    'createdAt',
    'description',
    'id',
    'name',
    'status',
    'updatedAt',
  ] as const
  $columns = AdminRoleSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare status: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AdminUserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'roleId', 'updatedAt', 'userId'] as const
  $columns = AdminUserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AdminUserSchema extends BaseModel {
  static $columns = [
    'avatar',
    'createdAt',
    'email',
    'fullName',
    'id',
    'isSuperAdmin',
    'lastLoginAt',
    'lastLoginIp',
    'mobile',
    'password',
    'profile',
    'status',
    'updatedAt',
    'username',
  ] as const
  $columns = AdminUserSchema.$columns
  @column()
  declare avatar: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSuperAdmin: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare lastLoginIp: string | null
  @column()
  declare mobile: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare profile: string | null
  @column()
  declare status: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class AttachmentRelationSchema extends BaseModel {
  static $columns = [
    'attachmentId',
    'businessId',
    'businessType',
    'createdAt',
    'fieldName',
    'id',
    'sort',
  ] as const
  $columns = AttachmentRelationSchema.$columns
  @column()
  declare attachmentId: number
  @column()
  declare businessId: string
  @column()
  declare businessType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fieldName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sort: number
}

export class AttachmentSchema extends BaseModel {
  static $columns = [
    'boundAt',
    'createdAt',
    'deletedAt',
    'duration',
    'errorMessage',
    'expiresAt',
    'extension',
    'fileType',
    'hash',
    'height',
    'id',
    'isComplete',
    'lastUsedAt',
    'mimeType',
    'objectKey',
    'originalName',
    'parentAttachmentId',
    'size',
    'status',
    'storageDisk',
    'storagePath',
    'updatedAt',
    'uploadMode',
    'uploadToken',
    'uploaderId',
    'url',
    'uuid',
    'width',
  ] as const
  $columns = AttachmentSchema.$columns
  @column.dateTime()
  declare boundAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare duration: number | null
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare extension: string | null
  @column()
  declare fileType: string
  @column()
  declare hash: string | null
  @column()
  declare height: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isComplete: boolean
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare mimeType: string
  @column()
  declare objectKey: string | null
  @column()
  declare originalName: string
  @column()
  declare parentAttachmentId: number | null
  @column()
  declare size: bigint | number
  @column()
  declare status: string
  @column()
  declare storageDisk: string
  @column()
  declare storagePath: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadMode: string
  @column()
  declare uploadToken: string
  @column()
  declare uploaderId: number
  @column()
  declare url: string | null
  @column()
  declare uuid: string
  @column()
  declare width: number | null
}

export class SmsCodeSchema extends BaseModel {
  static $columns = [
    'attemptCount',
    'codeHash',
    'createdAt',
    'expiresAt',
    'id',
    'mobile',
    'providerResponse',
    'requestIp',
    'scene',
    'sendStatus',
    'templateCode',
    'updatedAt',
    'usedAt',
  ] as const
  $columns = SmsCodeSchema.$columns
  @column()
  declare attemptCount: number
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mobile: string
  @column()
  declare providerResponse: string | null
  @column()
  declare requestIp: string | null
  @column()
  declare scene: string
  @column()
  declare sendStatus: string
  @column()
  declare templateCode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
}

export class UploadChunkSchema extends BaseModel {
  static $columns = [
    'chunkIndex',
    'etag',
    'hash',
    'id',
    'isComplete',
    'size',
    'storagePath',
    'uploadSessionId',
    'uploadedAt',
  ] as const
  $columns = UploadChunkSchema.$columns
  @column()
  declare chunkIndex: number
  @column()
  declare etag: string | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isComplete: boolean
  @column()
  declare size: number
  @column()
  declare storagePath: string
  @column()
  declare uploadSessionId: number
  @column.dateTime()
  declare uploadedAt: DateTime
}

export class UploadSessionSchema extends BaseModel {
  static $columns = [
    'attachmentId',
    'chunkSize',
    'chunkTotal',
    'createdAt',
    'errorMessage',
    'expiresAt',
    'fileHash',
    'fileSize',
    'id',
    'mimeType',
    'originalName',
    'status',
    'storageUploadId',
    'updatedAt',
    'uploadId',
    'uploadToken',
    'uploadedChunks',
    'uploaderId',
  ] as const
  $columns = UploadSessionSchema.$columns
  @column()
  declare attachmentId: number
  @column()
  declare chunkSize: number
  @column()
  declare chunkTotal: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errorMessage: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare fileHash: string | null
  @column()
  declare fileSize: bigint | number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare status: string
  @column()
  declare storageUploadId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uploadId: string
  @column()
  declare uploadToken: string
  @column()
  declare uploadedChunks: number
  @column()
  declare uploaderId: number
}
